### ISSUE TITLE
Metrics are not being pushed to the service

### ISSUE THREAD

**Issue by kjgarza** [datacite/keeshond#1]
The dashboard is not displaying metrics, it seems that the reason is the database is full 

![image](https://user-images.githubusercontent.com/1092861/176179473-fb715211-e28b-4103-bbaf-4007ce175d02.png)

**Comment by richardhallett** [comment]
This error isn't related to the microservice but because the clickhouse service got full diskspace.
I've fixed this and the dashboard should now display.
There is however a seperate issue for clickhouse I've raised here: https://github.com/datacite/datacite/issues/1502
